// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzpqVcB7iMHZdm8r7ynB59abqE3KFReQ',
    appId: '1:215143484242:web:86f5aed5dea5864bde088b',
    messagingSenderId: '215143484242',
    projectId: 'rehome-525e5',
    authDomain: 'rehome-525e5.firebaseapp.com',
    storageBucket: 'rehome-525e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe7ZdSrSqoY9TDHl_cCQRrlDWs9uNG19Y',
    appId: '1:215143484242:android:1f981b9053d03c8dde088b',
    messagingSenderId: '215143484242',
    projectId: 'rehome-525e5',
    storageBucket: 'rehome-525e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTlFfcHSVk_sXUSyD8W7MstEFI50dQ0s',
    appId: '1:215143484242:ios:4f391cea03f5d200de088b',
    messagingSenderId: '215143484242',
    projectId: 'rehome-525e5',
    storageBucket: 'rehome-525e5.appspot.com',
    iosBundleId: 'com.adoption.adoptionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByTlFfcHSVk_sXUSyD8W7MstEFI50dQ0s',
    appId: '1:215143484242:ios:f0e070ca5f71cf76de088b',
    messagingSenderId: '215143484242',
    projectId: 'rehome-525e5',
    storageBucket: 'rehome-525e5.appspot.com',
    iosBundleId: 'com.example.adoptionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSzpqVcB7iMHZdm8r7ynB59abqE3KFReQ',
    appId: '1:215143484242:web:a97d047f5dcfee36de088b',
    messagingSenderId: '215143484242',
    projectId: 'rehome-525e5',
    authDomain: 'rehome-525e5.firebaseapp.com',
    storageBucket: 'rehome-525e5.appspot.com',
  );
}
